# Generated by Django 4.2.19 on 2025-02-23 16:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("res_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name="education", name="end_date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="experience", name="end_date", field=models.DateField(),
        ),
    ]
